services:
  # SteamCMD service for downloading game files
  steamcmd:
    image: cm2network/steamcmd:latest
    volumes:
      - ./_data/game-files:/game
    command: >
      bash -c "/home/steam/steamcmd/steamcmd.sh +force_install_dir /game +login anonymous +app_update 294420 validate +quit"


  # Builder service for compiling the mod
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - ./:/app
      - ./_data/7dtd-binaries:/app/_data/7dtd-binaries
      - ./_data/build:/app/bin
      - ./_data/lib:/app/lib
    command: ["bash", "-c", "echo 'Builder container ready' && tail -f /dev/null"]

  # Game server service (for reference/testing)
  7dtdserver:
    image: vinanrra/7dtd-server
    environment:
      - START_MODE=3
      - PUID=1000
      - PGID=1000
      - TimeZone=Europe/Brussels
      - VERSION=latest_experimental
    volumes:
      - ./_data/ServerFiles:/home/sdtdserver/serverfiles/
      - ./_data/7DaysToDie:/home/sdtdserver/.local/share/7DaysToDie/
      - ./_data/7d2d-log:/home/sdtdserver/log/
    ports:
      - "26900-26902:26900-26902/udp"
      - "26900:26900/tcp"
      - "8080-8083:8080-8083/tcp"

  # Dependency service for fetching and building dependencies
  deps:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - ./_data/7dtd-binaries:/binaries
      - ./_data/lib:/app/lib
    command: >
      bash -c "
        git clone https://github.com/sta/websocket-sharp.git /tmp/websocket-sharp &&
        cd /tmp/websocket-sharp &&
        xbuild /p:Configuration=Release websocket-sharp.sln &&
        cp /tmp/websocket-sharp/Example/bin/Release/websocket-sharp.dll /binaries/ &&
        cp /tmp/websocket-sharp/Example/bin/Release/websocket-sharp.dll /app/lib/ &&
        nuget install Newtonsoft.Json -Version 13.0.1 -OutputDirectory /tmp &&
        cp -r /tmp/Newtonsoft.Json.13.0.1 /binaries/"