services:
  7dtdserver:
    image: vinanrra/7dtd-server
    container_name: 7dtdserver
    environment:
      - START_MODE=3 # Change between START MODES
      - PUID=1000 # Remember to use same as your user
      - PGID=1000 # Remember to use same as your user
      - TimeZone=Europe/Brussels # Optional - Change Timezone
      - UPDATE_MODS=NO # Optional - This will allow mods to be update on start, each mod also need to have XXXX_UPDATE=YES to update on start
      - ALLOC_FIXES=NO # Optional - Install ALLOC FIXES
      - ALLOC_FIXES_UPDATE=NO # Optional - Update Allocs Fixes before server start
      - CPM=NO # Optional - CSMM Patron's Mod (CPM)
      - CPM_UPDATE=NO # Optional - Update BepInEx before server start
      - BACKUP=NO # Optional - Backup server at 5 AM
      - MONITOR=NO # Optional - Keeps server up if crash
      - VERSION=latest_experimental
    volumes:
      - ./_data/7DaysToDie:/home/sdtdserver/.local/share/7DaysToDie/
      - ./_data/LGSM-Config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver
      - ./_data/ServerFiles:/home/sdtdserver/serverfiles/ # Optional - serverfiles folder
      - ./_data/log:/home/sdtdserver/log/ # Optional - Logs folder
      - ./_data/backups:/home/sdtdserver/lgsm/backup/ # Optional - If BAKCUP=NO, backups folder
    ports:
      - 26900:26900/tcp # Default game ports
      - 26900:26900/udp # Default game ports
      - 26901:26901/udp # Default game ports
      - 26902:26902/udp # Default game ports
      - 8080:8080/tcp # OPTIONAL - WEBADMIN
      - 8081:8081/tcp # OPTIONAL - TELNET
      - 8082:8082/tcp # OPTIONAL - WEBSERVER https://7dtd.illy.bz/wiki/Server%20fixes
      - 8083:8083/tcp # OPTIONAL - CPM (?)
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - ./:/app
      - ./_data/ServerFiles:/game-server-files
      - ./_data/build:/app/bin